//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FO_ERM_ISE
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeitType
    {
        public FeitType()
        {
            this.PredicaatDeel = new HashSet<PredicaatDeel>();
            this.Relatietype = new HashSet<Relatietype>();
            this.Segment = new HashSet<Segment>();
        }
    
        public int dataModelNummer { get; set; }
        public string feitTypeCode { get; set; }
        public string verwoording { get; set; }
    
        public virtual DataModel DataModel { get; set; }
        public virtual ICollection<PredicaatDeel> PredicaatDeel { get; set; }
        public virtual ICollection<Relatietype> Relatietype { get; set; }
        public virtual ICollection<Segment> Segment { get; set; }
    }
}
