//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FO_ERM_ISE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FO_ERMEntities1 : DbContext
    {
        public FO_ERMEntities1()
            : base("name=FO_ERMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attribuut> Attribuut { get; set; }
        public virtual DbSet<DataModel> DataModel { get; set; }
        public virtual DbSet<EntiteitType> EntiteitType { get; set; }
        public virtual DbSet<FeitType> FeitType { get; set; }
        public virtual DbSet<Kardinaliteit> Kardinaliteit { get; set; }
        public virtual DbSet<PredicaatDeel> PredicaatDeel { get; set; }
        public virtual DbSet<Relatietype> Relatietype { get; set; }
        public virtual DbSet<RelatieTypeOnderdeel> RelatieTypeOnderdeel { get; set; }
        public virtual DbSet<Segment> Segment { get; set; }
        public virtual DbSet<SegmentDeel> SegmentDeel { get; set; }
        public virtual DbSet<VoorbeeldData> VoorbeeldData { get; set; }
    }
}
