//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FO_ERM_ISE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardinaliteit
    {
        public Kardinaliteit()
        {
            this.RelatieTypeOnderdeel = new HashSet<RelatieTypeOnderdeel>();
        }
    
        public string minimaleKardinaliteit { get; set; }
        public string maximaleKardinaliteit { get; set; }
    
        public virtual ICollection<RelatieTypeOnderdeel> RelatieTypeOnderdeel { get; set; }
    }
}
