//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FO_ERM_ISE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relatietype
    {
        public Relatietype()
        {
            this.RelatieTypeOnderdeel = new HashSet<RelatieTypeOnderdeel>();
        }
    
        public int dataModelNummer { get; set; }
        public string relatieTypeNaam { get; set; }
        public string feitTypeCode { get; set; }
    
        public virtual DataModel DataModel { get; set; }
        public virtual FeitType FeitType { get; set; }
        public virtual ICollection<RelatieTypeOnderdeel> RelatieTypeOnderdeel { get; set; }
    }
}
