//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FO_ERM_ISE
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatieTypeOnderdeel
    {
        public int dataModelNummer { get; set; }
        public string relatieTypeNaam { get; set; }
        public short onderdeelNummer { get; set; }
        public string minimaleKardinaliteit { get; set; }
        public string maximaleKardinaliteit { get; set; }
        public int entiteitTypeNummer { get; set; }
        public bool afhankelijk { get; set; }
    
        public virtual EntiteitType EntiteitType { get; set; }
        public virtual Kardinaliteit Kardinaliteit { get; set; }
        public virtual Relatietype Relatietype { get; set; }
    }
}
