//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FO_ERM_ISE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoorbeeldData
    {
        public int dataModelNummer { get; set; }
        public int entiteitNummer { get; set; }
        public int attribuutNummer { get; set; }
        public int rijNummer { get; set; }
        public string data { get; set; }
    
        public virtual Attribuut Attribuut { get; set; }
    }
}
